name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.5' # Specify your Go version

    - name: Build
      run: go build ./...
    
    - name: Run controller tests
      run: go test -v ./internal/controller/...

